### PR TITLE
fixed some clippy warnings

### PR DESCRIPTION
**Pull request by llogiq**
This combines two if-conditions, pulls an else-if together and adds a bunch of Default impls.

### CODE REVIEW

**Comment by Amanieu** [comment]
You need a manual implementation of `Default` for the generic `ThreadParker`.

**Comment by Amanieu** [comment]
I've fixed a few more clippy lints, and I think the rest just aren't worth fixing. In particular all those `Default` implementations are never going to be used since these types are internal to the library.

**Comment by llogiq** [comment]
That's a good observation. Do you think we should reduce the scope of that lint to public types?

**Comment by Amanieu** [comment]
Yes that would probably be a good idea.

**Pull request closed without merging**
