### PR TITLE
deps: update to windows-sys 0.36

### PR DESCRIPTION
**Pull request by poliorcetics**

### CODE REVIEW

**Comment by poliorcetics** [comment]
This is a separate PR from #337 because some people will probably want a dep on 0.35 and others a dep on 0.36, to avoid duplicate dependencies in their tree.

As such, #337 should be merged first, a version released, then this one and another version released

**Comment by poliorcetics** [comment]
See also https://github.com/microsoft/windows-rs/issues/1720

**Comment by kennykerr** [comment]
tokio/mio just took a dependency on 0.36 so that may be a good version to rally around for the time being.

https://github.com/tokio-rs/mio/pull/1569

**Comment by Amanieu** [comment]
I'm just going to merge this one and make a single release. This version churn is quite annoying, and if it continues then I'm considering just switching back to winapi.

**Comment by kennykerr** [comment]
Sorry for the annoyance. I'll probably exclude `windows-sys` from the regular 3-week release cadence that we've been on to allow the current version (0.36) to establish itself.

**Pull request merged**
