### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This PR adds GItHub Actions CI, which simplifies the current CI setup to a single script, and runs nearly all in parallel. This is blocked on #228 being resolved.

[z]: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Replacing.20mpsc/near/197012141

### CODE REVIEW

**Comment by Amanieu** [comment]
Can you delete the old travis and appveyor configs? I presume they are no longer needed.

**Comment by XAMPPRocky** [comment]
They aren't but I wanted to leave the option of adding github actions and removing the old ci as separate steps, I'm happy to also remove if you're good with it though.

**Comment by Amanieu** [comment]
I'm happy to just remove the old CI, it's much slower than GHA.

**Comment by XAMPPRocky** [comment]
Done.

**Comment by Amanieu** [comment]
Can you update bors.toml to use GHA instead of travis?

**Comment by XAMPPRocky** [comment]
Done.

**Comment by Amanieu** [comment]
Thanks!

**Pull request merged**
