### PR TITLE
Improve benchmark reporting

### PR DESCRIPTION
**Pull request by jynnantonix**
When benchmarking a synchronization primitive, raw throughput is not the
only statistic that matters. For example, it is also important that
threads do not starve waiting to acquire a lock.

Improve the benchmark reporting so that it reports the throughput per
thread per second.  This makes it possible to compare benchmarks across
different numbers of threads.  Without this, benchmark runs with more
threads would naturally appear to have higher throughput.  Additionally,
include the median and standard deviation for the throughput per thread
per second so that starvation issues become more apparent.

Signed-off-by: Chirantan Ekbote <chirantan@google.com>

### CODE REVIEW

**Comment by Amanieu** [comment]
Thanks!

From some quick tests, it seems that parking_lot has higher variance than the standard mutex, but even the slowest thread is still many time faster than the standard mutex.

**Comment by jynnantonix** [comment]
I'm curious what parameters you used.  For example, here's a benchmark run I tried with `target/release/mutex 10:40:5 100 1000 3`:

```
- Running with 10 threads
- 100 iterations inside lock, 1000 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |    216.674 kHz |    219.557 kHz |     33.432 kHz
std::sync::Mutex     |    117.422 kHz |    117.464 kHz |      0.273 kHz
pthread_mutex_t      |    137.189 kHz |    137.258 kHz |      0.593 kHz
- Running with 15 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |    136.945 kHz |    136.998 kHz |      4.211 kHz
std::sync::Mutex     |     82.138 kHz |     82.117 kHz |      0.266 kHz
pthread_mutex_t      |    104.025 kHz |    103.943 kHz |      0.677 kHz
- Running with 20 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     57.560 kHz |     57.465 kHz |      0.863 kHz
std::sync::Mutex     |     54.101 kHz |     54.183 kHz |      0.353 kHz
pthread_mutex_t      |     66.736 kHz |     66.769 kHz |      0.312 kHz
- Running with 25 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     15.639 kHz |     15.676 kHz |      0.357 kHz
std::sync::Mutex     |     39.558 kHz |     39.547 kHz |      0.224 kHz
pthread_mutex_t      |     53.197 kHz |     53.227 kHz |      0.372 kHz
- Running with 30 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     11.333 kHz |     11.337 kHz |      0.151 kHz
std::sync::Mutex     |     36.135 kHz |     36.573 kHz |      0.716 kHz
pthread_mutex_t      |     44.187 kHz |     44.240 kHz |      0.482 kHz
- Running with 35 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     12.069 kHz |     12.086 kHz |      0.223 kHz
std::sync::Mutex     |     31.048 kHz |     31.088 kHz |      0.197 kHz
pthread_mutex_t      |     37.611 kHz |     37.571 kHz |      0.239 kHz
- Running with 40 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      8.193 kHz |      8.221 kHz |      0.183 kHz
std::sync::Mutex     |     26.376 kHz |     26.403 kHz |      0.187 kHz
pthread_mutex_t      |     32.834 kHz |     32.827 kHz |      0.253 kHz
```

Personally, I think that if the number of iterations (both inside and outside the mutex) is too small, the benchmark runs into scheduler issues where threads get scheduled at exactly the right (or wrong) time, which can really skew the results.  Greatly increasing the number of iterations seems smooth out these problems.  This is what I get for `target/release/mutex 10:40:5 1000 100000 7`:

```
- Running with 10 threads
- 1000 iterations inside lock, 100000 iterations outside lock
- 7 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.848 kHz |      3.861 kHz |      0.038 kHz
std::sync::Mutex     |      3.966 kHz |      3.970 kHz |      0.014 kHz
pthread_mutex_t      |      3.965 kHz |      3.956 kHz |      0.026 kHz
- Running with 15 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.829 kHz |      3.825 kHz |      0.009 kHz
std::sync::Mutex     |      3.924 kHz |      3.925 kHz |      0.010 kHz
pthread_mutex_t      |      3.924 kHz |      3.927 kHz |      0.012 kHz
- Running with 20 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.798 kHz |      3.803 kHz |      0.023 kHz
std::sync::Mutex     |      3.927 kHz |      3.928 kHz |      0.004 kHz
pthread_mutex_t      |      3.929 kHz |      3.931 kHz |      0.005 kHz
- Running with 25 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.810 kHz |      3.818 kHz |      0.012 kHz
std::sync::Mutex     |      3.903 kHz |      3.902 kHz |      0.013 kHz
pthread_mutex_t      |      3.898 kHz |      3.898 kHz |      0.010 kHz
- Running with 30 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.796 kHz |      3.797 kHz |      0.017 kHz
std::sync::Mutex     |      3.847 kHz |      3.847 kHz |      0.020 kHz
pthread_mutex_t      |      3.889 kHz |      3.892 kHz |      0.025 kHz
- Running with 35 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.461 kHz |      3.439 kHz |      0.127 kHz
std::sync::Mutex     |      3.555 kHz |      3.553 kHz |      0.043 kHz
pthread_mutex_t      |      3.558 kHz |      3.567 kHz |      0.051 kHz
- Running with 40 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |      3.031 kHz |      3.030 kHz |      0.154 kHz
std::sync::Mutex     |      3.124 kHz |      3.116 kHz |      0.058 kHz
pthread_mutex_t      |      3.116 kHz |      3.123 kHz |      0.056 kHz

```

parking_lot is still pretty nice since it's pure rust but I think it's a bit disingenuous to claim that it's significantly faster than std::sync or pthread_mutex_t.

**Comment by Amanieu** [comment]
The trouble with large iteration counts is that the overhead of the mutex is outweighed by that of the iterations, so you're only really measuring the time to run the iterations outside the loop.

I usually run the benchmarks with very small iteration counts, which makes the performance difference more apparent:
```
$ cargo run --features nightly --release --bin mutex 1:8 1 0 1
     Running `target/release/mutex 1:8 1 0 1`
- Running with 1 threads
- 1 iterations inside lock, 0 iterations outside lock
- 1 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  61540.547 kHz |  61540.547 kHz |      0.000 kHz
std::sync::Mutex     |  49569.378 kHz |  49569.378 kHz |      0.000 kHz
pthread_mutex_t      |  36887.178 kHz |  36887.178 kHz |      0.000 kHz
- Running with 2 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  30084.914 kHz |  55646.305 kHz |  25561.392 kHz
std::sync::Mutex     |   3272.383 kHz |   3332.871 kHz |     60.488 kHz
pthread_mutex_t      |   6609.229 kHz |   7221.714 kHz |    612.486 kHz
- Running with 3 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  20583.291 kHz |  16581.516 kHz |   5924.963 kHz
std::sync::Mutex     |   4724.712 kHz |   4697.993 kHz |     50.629 kHz
pthread_mutex_t      |   4215.501 kHz |   4341.646 kHz |    231.434 kHz
- Running with 4 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  14948.601 kHz |  17988.333 kHz |   5304.999 kHz
std::sync::Mutex     |   1746.598 kHz |   1747.875 kHz |      9.873 kHz
pthread_mutex_t      |   2454.970 kHz |   2436.789 kHz |     50.779 kHz
- Running with 5 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |  11639.496 kHz |  14031.581 kHz |   5333.297 kHz
std::sync::Mutex     |   1410.649 kHz |   1362.254 kHz |    140.506 kHz
pthread_mutex_t      |   1871.940 kHz |   1881.428 kHz |     31.267 kHz
- Running with 6 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   9463.156 kHz |  12723.068 kHz |   5512.843 kHz
std::sync::Mutex     |   1008.886 kHz |    993.176 kHz |     64.600 kHz
pthread_mutex_t      |   1510.864 kHz |   1499.174 kHz |     35.440 kHz
- Running with 7 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   7976.786 kHz |  10303.688 kHz |   4267.379 kHz
std::sync::Mutex     |    874.732 kHz |    865.364 kHz |     21.862 kHz
pthread_mutex_t      |   1275.333 kHz |   1275.674 kHz |      7.835 kHz
- Running with 8 threads
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   6832.803 kHz |   7547.992 kHz |   2320.447 kHz
std::sync::Mutex     |    832.020 kHz |    830.773 kHz |      5.924 kHz
pthread_mutex_t      |   1137.648 kHz |   1138.072 kHz |     18.066 kHz
```

**Comment by jynnantonix** [comment]
Sure, but that's only useful if the performance difference on a small iteration count is indicative of a equivalent performance difference on a realistic workload.  I just don't think that's true here.

Having a larger iteration count outside the lock also allows you to benchmark how well the mutex performs under different levels of contention, which is an important metric.

**Comment by jynnantonix** [comment]
Here are some more benchmark runs with small iterations:

```
- Running with 31 threads
- 10 iterations inside lock, 10 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     26.780 kHz |     26.651 kHz |      2.428 kHz
std::sync::Mutex     |    117.746 kHz |    117.706 kHz |      1.134 kHz
pthread_mutex_t      |    161.839 kHz |    161.896 kHz |      6.377 kHz
```

```
- Running with 31 threads
- 10 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     18.707 kHz |     18.393 kHz |      3.028 kHz
std::sync::Mutex     |    143.058 kHz |    142.411 kHz |      2.248 kHz
pthread_mutex_t      |    225.622 kHz |    225.466 kHz |      4.919 kHz
```

```
- Running with 31 threads
- 5 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     77.167 kHz |     75.560 kHz |      9.646 kHz
std::sync::Mutex     |    182.181 kHz |    182.080 kHz |      2.596 kHz
pthread_mutex_t      |    307.976 kHz |    309.987 kHz |     12.468 kHz
```

I think the fact that this library is pure rust is a strong enough point in its favor that you don't need to mislead people into thinking that it's faster than std::sync and pthread_mutex_t.

**Comment by ParadoxSpiral** [comment]
@jynnantonix 
Can't reproduce your numbers.

```
- Running with 31 threads
- 10 iterations inside lock, 10 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |    601.607 kHz |    603.050 kHz |     16.667 kHz
std::sync::Mutex     |    196.293 kHz |    196.254 kHz |      2.745 kHz
pthread_mutex_t      |    217.614 kHz |    216.507 kHz |      3.621 kHz
```

```
- Running with 31 threads
- 10 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   1115.915 kHz |   1110.412 kHz |     33.014 kHz
std::sync::Mutex     |    209.921 kHz |    210.163 kHz |      3.365 kHz
pthread_mutex_t      |    246.705 kHz |    246.722 kHz |      3.684 kHz
```

```
- Running with 31 threads
- 5 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |   1783.181 kHz |   1780.899 kHz |     37.575 kHz
std::sync::Mutex     |    237.482 kHz |    237.196 kHz |      3.736 kHz
pthread_mutex_t      |    288.012 kHz |    288.432 kHz |      3.005 kHz
```

**Comment by Amanieu** [comment]
I'm also getting results similar to those of @ParadoxSpiral.

@jynnantonix could you tell me a few things about your system:
- What OS are you running?
- What CPU model do you have? How many cores?
- Are you sure you are compiling with optimizations enabled? (`--release`) Are you compiling with nightly features enabled? (`--feature nightly`)

For reference, here is the command I am using (from the `benchmark` directory):
`cargo run --features nightly --release --bin mutex 31 10 10 3`

**Comment by Amanieu** [comment]
Also for reference, my results are on x86_64 Linux, with an 8 core i7-6700HQ at 2.6GHz.

**Comment by hexsel** [comment]
Just for a reference, here are the results from a MacBookPro, mid 2015, Core i7, 16GB:

- Running with 31 threads
- 10 iterations inside lock, 10 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.
parking_lot::Mutex   |    622.464 kHz |    622.705 kHz |      7.187 kHz
std::sync::Mutex     |      8.824 kHz |      8.821 kHz |      0.015 kHz
pthread_mutex_t      |      8.954 kHz |      8.952 kHz |      0.009 kHz

- Running with 31 threads
- 10 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.
parking_lot::Mutex   |   1135.880 kHz |   1133.437 kHz |     30.862 kHz
std::sync::Mutex     |      8.974 kHz |      8.972 kHz |      0.011 kHz
pthread_mutex_t      |      9.198 kHz |      9.196 kHz |      0.009 kHz

- Running with 31 threads
- 5 iterations inside lock, 0 iterations outside lock
- 3 seconds per test
        name         |    average     |     median     |    std.dev.
parking_lot::Mutex   |   1518.602 kHz |   1519.831 kHz |     27.636 kHz
std::sync::Mutex     |      8.998 kHz |      8.997 kHz |      0.000 kHz
pthread_mutex_t      |      9.197 kHz |      9.191 kHz |      0.035 kHz

Anyone know why the alternatives are so bad on OSX?

**Comment by Amanieu** [comment]
@hexsel OSX is known to have a very slow pthread_mutex_t since it uses a fair mutex, which is a lot slower than an unfair mutex. Linux and Windows both use unfair mutexes, and are therefore not affected by this problem.

**Comment by jynnantonix** [comment]
> What OS are you running?

Ubuntu Trusty

> What CPU model do you have? How many cores?

Intel Xeon CPU E5-2690 0 @ 2.90GHz.  32 cores.

> Are you sure you are compiling with optimizations enabled? (--release) Are you compiling with nightly features enabled? (--feature nightly)

Yes, that was a release build but it was on stable, not nightly.

**Comment by jynnantonix** [comment]
I also realize that I may have come across as more confrontational than I intended.  I think this library is really nice and I would love to see a world where the synchronization primitives in the standard library are pure rust.  However, I want that to be because the rust implementation is genuinely superior and not because we just didn't measure the right things.

**Pull request merged**
