### PR TITLE
Misc clippy fixes

### PR DESCRIPTION
**Pull request by faern**
I went over the crates with Clippy. Some suggested changes are only stylistic, others more optimization oriented. The commit messages should hopefully explain well enough why each change was made. Otherwise see what clippy says on current master :)

I left some warnings, since the suggested changes were not really objectively better, or possibly larger than what I wanted to do right now.

### CODE REVIEW

**Comment by faern** [comment]
Also pulled in the removal of the `autocfg` dependency that we stopped using over in #189

**Comment by Amanieu** [comment]
This is technically a breaking change, but we're about to make a major version bump anyways...

**Comment by faern** [comment]
My thought exactly. I'm bumping versions and drafting a changelog at the moment. Will submit soon.

**Pull request merged**
