### PR TITLE
Update redox_syscall dependency version

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Thanks for the quick merge. Is there any current thought as to when the next release might be?

**Comment by bjorn3** [comment]
Redox OS is in the process of moving from the redox_syscall crate to the libredox crate to provide a more stable ABI while still allowing the syscall ABI to evolve: https://crates.io/crates/libredox

**Comment by Amanieu** [comment]
I don't have a plan to make a release any time soon unless you specifically need it. However it would be nice to move to libredox first if it's ready for use.

**Comment by bjorn3** [comment]
> if it's ready for use.

cc @4lDO2

**Comment by alex** [comment]
Just wanted to pass along a thank you for the release!

**Pull request merged**
