### PR TITLE
Provide correct implementation of AtomicElisionExt for x32

### PR DESCRIPTION
**Pull request by glaubitz**
The assembly implementation of AtomicElisionExt does not build on x32 as the x86_64 assembly code does not build there.

While it should be generally possible to write an assembly implementation of AtomicElisionExt for x32 later - and, FWIW, for all the other architectures - this change will at least fix the build failure of ```parking_lot``` on x32.

### CODE REVIEW

**Comment by Amanieu** [comment]
Does changing `cmpxchgq` to `cmpxchgl` fix this by any chance?

**Comment by glaubitz** [comment]
> Does changing cmpxchgq to cmpxchgl fix this by any chance?

Let me try ...

**Comment by glaubitz** [comment]
Ok, I have updated the PR. ```cmpxchgl``` does work for x32 while ```cmpxchgq``` is the correct version for x86_64.

**Comment by Amanieu** [comment]
This is now included in the latest version of parking_lot (0.5.4).

**Pull request merged**
