### PR TITLE
Staging for parking_lot 0.9.0,  _core 0.6.0 and lock_api 0.3.1 releases

### LINKED ISSUE #158: Release new parking_lot_core?
I was personally pleased to see this particular change released, as mentioned in the CHANGELOG:

``` txt
0.8.1 (2019-07-03)
==================

- Removed dependency on rand crate. (#144)
```

Its also mentioned in final comments of #138. I saw this release was yanked per #156, but I also noticed that localized PRNG was actually added to _parking_lot_core_ (not _parking_lot_) and there has been no new release attempt for _parking_lot_core_.  This is the git hash for the last parking_lot_core-0.5.0 release:

`cat ~/.cargo/registry/src/*/parking_lot_core-0.5.0/.cargo_vcs_info.json`

``` json
{
  "git": {
    "sha1": "3259fd72e0d76e9c9a6f31ff41a996648fe9ccfa"
  }
}
```

Friendly suggestion: its a pretty standard approach for a git repo workspace of multiple crates to have crate specific tags, e.g.:

`git tag core-0.5.0 3259fd72`

…and then either give it its own core/CHANGELOG.md, or seperately give it its own version sections in the top-level CHANGELOG.

Here is what has changed between that release and master in the core crate:

https://github.com/Amanieu/parking_lot/compare/3259fd72...master

Or `git log 3259fd72.. -- core` produces:

7b403d3 Use hint::unreachable_unchecked instead of Void enum
013e482 Add new wasm thread parker for non-atomic libstds
a31781b Rename existing wasm ThreadParker
3a395e1 Merge pull request #140 from faern/fix-feedback-from-libstd-1
92498d5 Remove invalid use of word "random"
757a640 Use incrementing index instead of ptr address as seed
4d78285 Implement own xorshift PRNG to avoid rand dependency
6607fd3 Fix CloudABI ThreadParker
c763967 Remove not needed unsafe blocks
5e2d677 Use FUTEX_ constants from libc
3132b95 Make Android use futex based parker
2fb27d3 Create a ThreadParker trait, to unify API
c162cfc Remove #[inline(never)]
f9f951b Format comment
c8c5041 Use impl trait instead of generic in park
c775469 Simplify unlock_bucket_pair
4594729 Run latest rustfmt (1.2.2-nightly)

Without knowing more, I would cautiously suggest this warrants a parking_lot_core-0.6.0 release, with the presumed (suggested in #156) to be released parking_lot_0.9.0 depending on that. If you release this as parking_lot_core-0.5.1, it would mean its compatible for use with the existing parking_lot-0.8.0 and that likely would warrant testing. 

If it would be helpful, I'm happy to provide a PR with those suggested changes to the two Cargo.toml.  I'm not sure I'm well enough versed to completely fix up the CHANGELOG(s) though.  Thanks for all your work on this project!

### PR DESCRIPTION
**Pull request by dekellum**
This includes all necessary version changes and overhauls the CHANGELOG to show more recent releases for all three crates (_parking_lot_, _parking_lot_core_, _lock_api_). Before releasing, the top  `(TBD)` should be replaced with the current date and tags for all crates added.    I also request that you add the following tags to this repo retroactively:

``` bash
git tag core-0.5.0 3259fd72e0d76e9c9a6f31ff41a996648fe9ccfa
git tag lock_api-0.1.5 2653619a613bc12dd6ab486f789d98956b65cdf0
git tag lock_api-0.2.0 3259fd72e0d76e9c9a6f31ff41a996648fe9ccfa
git tag lock_api-0.3.0 ace8280969b6362c3f3753506d90122c358de580
```

Fixes #158

### CODE REVIEW

**Comment by dekellum** [comment]
The [rendered CHANGELOG](https://github.com/Amanieu/parking_lot/blob/64747def760a1b5e909e020b6c63e25ab47f2691/CHANGELOG.md) for preview.

**Comment by dekellum** [comment]
The appveryor CI failure appears unrelated?

``` txt
error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)
```

**Comment by dekellum** [comment]
master branch commit da16c2c is a fix to lock_api, so bumped version to 0.3.1, merged it here and updated CHANGELOG for that.

**Comment by dekellum** [comment]
@Amanieu do you also want to yank lock_api 0.3.0, in light of the findings of da16c2c?

**Comment by Amanieu** [comment]
> @Amanieu do you also want to yank lock_api 0.3.0, in light of the findings of [da16c2c](https://github.com/Amanieu/parking_lot/commit/da16c2c7709e3c97df9b1ca34e2811f320dddec4)?

Good point, I just yanked it.

**Comment by Amanieu** [comment]
Thanks a lot for the help! I have published new crate versions and added new tags.

**Comment by matklad** [comment]
I am a little worried by 

>Rust 1.31 may continue to work for normal use of these releases.

`rand` bumping msrv is definitely not a parking_lot fault, but still, the end result is unfortunate. Can I rely on `parking_lot` working with `1.31.0` or not? If I can, I'd be happy to send a PR that updates readme and adds a compile-only CI job for 1.31.0.  I am also not against bumping msrv of reversed deps to 1.32.0, it's just unclear what is the current stance :)

**Comment by Amanieu** [comment]
Yes, parking_lot should work fine on 1.31. It's just that the tests don't compile because of rand (which is only a dev-dependency).

I am happy to accept a PR to clarify this in the README.

**Pull request merged**
